# Generated by Django 4.1.1 on 2022-10-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=20)),
                ('departureAirport', models.CharField(max_length=3)),
                ('arrivalAirport', models.CharField(max_length=3)),
                ('scheduledTime', models.TimeField()),
            ],
            options={
                'db_table': 'rotas',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=20)),
                ('scheduledDate', models.DateField()),
                ('realDate', models.DateField(null=True)),
                ('realTime', models.TimeField(null=True)),
                ('routeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.route')),
            ],
            options={
                'db_table': 'voos',
            },
        ),
    ]
