# Generated by Django 4.1.1 on 2022-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='routeCode',
            new_name='flightCode',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='routeCode',
            new_name='flightCode',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flightId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
