# Generated by Django 4.1.1 on 2022-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('userType', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
