# Generated by Django 4.1.2 on 2022-10-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='departureAirport',
        ),
    ]
