# Generated by Django 4.1.2 on 2022-11-05 00:54

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "flights.json")

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_load_fixture_routes'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
