# Generated by Django 4.1.2 on 2022-11-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_load_fixture_flights'),
    ]

    operations = [
    ]
