# Generated by Django 4.1.2 on 2022-11-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20221106_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='realDate',
            field=models.DateField(null=True, verbose_name='Data Real'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='realTime',
            field=models.TimeField(null=True, verbose_name='Horário Real'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.route', verbose_name='Rota'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduledDate',
            field=models.DateField(verbose_name='Data Prevista'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route',
            name='airline',
            field=models.CharField(max_length=20, verbose_name='Companhia'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrivalAirport',
            field=models.CharField(max_length=3, verbose_name='Aeroporto de Destino'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departureAirport',
            field=models.CharField(max_length=3, verbose_name='Aeroporto de Origem'),
        ),
        migrations.AlterField(
            model_name='route',
            name='flightCode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código de Voo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='scheduledTime',
            field=models.TimeField(verbose_name='Horário Previsto'),
        ),
    ]
