# Generated by Django 4.1.2 on 2022-11-06 12:49
from django.core.management import call_command
from django.db import migrations

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "flights.json")

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_flight_realdate_alter_flight_realtime_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
